/**
 * i18n module — every user-facing string in uz / ru / en.
 * `t` is a live binding: call setLocale() and re-render; all importers see the new language.
 * Demo content (topics, questions, names) comes from mockData/gameData and stays as backend data.
 */

export type Locale = 'uz' | 'ru' | 'en';

const uz = {
  // ── Dates ──────────────────────────────────────────────
  monthsFull: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
  monthsGen: ['yanvar', 'fevral', 'mart', 'aprel', 'may', 'iyun', 'iyul', 'avgust', 'sentabr', 'oktabr', 'noyabr', 'dekabr'],
  weekdaysShort: ['Du', 'Se', 'Chor', 'Pay', 'Ju', 'Sha', 'Yak'],
  weekdaysLong: ['dushanba', 'seshanba', 'chorshanba', 'payshanba', 'juma', 'shanba', 'yakshanba'],

  // ── Brand ──────────────────────────────────────────────
  brand: 'Phoenix Math School',
  version: 'Phoenix Math School · v1.0',

  // ── Auth ───────────────────────────────────────────────
  authWelcome: 'Xush kelibsiz',
  authSubtitle: 'Hisobingizga kiring',
  authIdLabel: 'ID raqam',
  authIdPlaceholder: '01234',
  authPasswordLabel: 'Parol',
  authPasswordPlaceholder: '••••••••',
  authSignIn: 'KIRISH',
  authForgot: 'Parolni unutdingizmi? Administratorga murojaat qiling.',
  authError: "ID yoki parol noto'g'ri. Qaytadan urinib ko'ring.",
  authShowPassword: "Parolni ko'rsatish",
  authHidePassword: 'Parolni yashirish',

  pwTitle: "Yangi parol o'rnating",
  pwBody: "Birinchi parol vaqtinchalik edi. Endi faqat o'zingiz biladigan parol kiriting.",
  pwNew: 'Yangi parol',
  pwRepeat: 'Takrorlang',
  pwRule8: 'Kamida 8 ta belgi',
  pwRuleDigit: 'Kamida 1 ta raqam',
  pwRuleMatch: 'Parollar mos keladi',
  pwSave: 'SAQLASH',

  bioTitle: 'Tez kirishni yoqasizmi?',
  bioBody: 'Har safar parol yozmaslik uchun.',
  bioFace: 'FACE ID NI YOQISH',
  bioPin: "4 xonali PIN o'rnatish",
  bioSkip: 'Hozir emas',

  pinTitle: 'PIN kodni kiriting',
  pinWrong: "PIN kod noto'g'ri",
  pinDelete: "O'chirish",
  pinFaceId: 'Face ID',

  // ── Tabs ───────────────────────────────────────────────
  tabToday: 'Bugun',
  tabLessons: 'Darslarim',
  tabBookings: 'Yozilish',
  tabProgress: 'Progress',
  tabProfile: 'Profil',
  tabAttendance: 'Davomat',
  tabPayments: "To'lovlar",

  // ── Student · Today ────────────────────────────────────
  todayGreeting: (name: string) => `Salom, ${name}`,
  todayLessonCaption: 'BUGUNGI DARS',
  todayNoLesson: "Bugun dars yo'q",
  todayNextLesson: 'Keyingi dars: ertaga 14:00',
  todayAllClear: 'Hammasi joyida 👍',
  todayAllClearBody: "Bugun bajarilmagan ish yo'q.",
  nextBookingHeader: 'KEYINGI YOZILISH',
  lastExamHeader: 'OXIRGI IMTIHON',
  weakPointBody: "O'qituvchingiz shu mavzuga yana bir dars kerak deb hisoblaydi.",
  weakPointCta: 'YOZILISH',
  finishHeader: 'TUGATISH KERAK',

  // ── Stats ──────────────────────────────────────────────
  statAttendance: 'Davomat',
  statHomework: 'Uy vazifasi',
  statTopics: 'Mavzular',
  statLessons: 'Darslar',
  statPresent: 'Keldim',
  statPresentParent: 'Keldi',

  // ── Lessons ────────────────────────────────────────────
  lessonsSubtitle: "Har bir dars va u qanday o'tgani",
  segAll: 'Hammasi',
  segAbsent: 'Kelmagan',
  segHomework: 'Uy vazifasi',
  lessonAttendance: 'Davomat',
  lessonHomework: 'Uy vazifasi',
  lessonConspect: 'Konspekt',
  lessonEngagement: 'Faollik',
  emptyLessonsTitle: 'Darslar hali belgilanmagan',
  emptyLessonsBody: "O'qituvchi davomatni belgilagach shu yerda ko'rinadi.",

  // ── Status labels ──────────────────────────────────────
  present: 'Keldi',
  late: 'Kech',
  absent: 'Kelmadi',
  unmarked: 'Belgilanmagan',
  hwDone: 'Bajarildi',
  hwNot: 'Bajarilmagan',
  hwPartial: 'Qisman',
  conspectFull: "To'liq",
  conspectPartial: 'Qisman',
  engHigh: 'Yuqori',
  engMedium: "O'rtacha",
  engLow: 'Past',

  // ── Bookings ───────────────────────────────────────────
  bookingsSubtitle: "Qo'shimcha dars uchun vaqt band qiling",
  quotaLine: (left: number, limit: number) => `Bu hafta ${limit} tadan ${left} tasi qoldi`,
  quotaSpent: 'Bu hafta limit tugadi. Dushanbadan yana yozilishingiz mumkin.',
  newBooking: 'YANGI YOZILISH',
  upcomingHeader: 'KELGUSI',
  pastHeader: "O'TGAN",
  bookingAttended: 'Qatnashdi',
  bookingMissed: 'Kelmadi',
  bookingCancelled: 'Bekor qilingan',
  bookingNeedsAnother: 'Yana bir dars kerak',
  bookingLocked: "O'zgartirish 12:00 da yopildi.",
  swipeCancel: 'Bekor qilish',
  emptyBookingsTitle: 'Hali yozilmagansiz',
  emptyBookingsBody: "Qo'shimcha dars uchun vaqt band qiling.",

  sheetNewBooking: 'Yangi yozilish',
  stepDate: 'SANA',
  stepTime: 'VAQT',
  stepPurpose: 'MAQSAD',
  purposePlaceholder: 'masalan: Kasrlar — maxrajni tenglash',
  purposeHint: 'Kamida 3 ta belgi.',
  confirm: 'TASDIQLASH',
  bookingConfirmed: 'Yozilish tasdiqlandi',
  cancelTitle: 'Yozilishni bekor qilasizmi?',
  cancelReasonLabel: 'Sabab (kamida 10 ta belgi)',
  cancelReasonPlaceholder: 'Nima uchun bekor qilyapsiz? (kamida 10 ta belgi)',
  cancelReasonHint: 'Kamida 10 ta, ko‘pi bilan 300 ta belgi.',
  cancelReasonMin: 'Sabab kamida 10 ta belgidan iborat bo‘lishi kerak',
  cancelConfirm: 'BEKOR QILISH',
  cancelBack: 'Qaytish',
  cancelKeep: 'Yozilishda qolish',
  bookingCancelledToast: 'Yozilish bekor qilindi',

  bookingTabBook: 'Yozilish',
  bookingTabMine: 'Mening darslarim',
  weeklyUsageTitle: 'Haftalik darslar',
  weeklyUsageRemaining: (rem: number) => `Qolgan: ${rem} ta dars`,
  weeklyUsageLimitReached: 'Haftalik limit to‘lgan',
  sessionsAvailable: 'Mavjud sessiyalar',
  noSlotsForDate: 'Ushbu sana uchun ochiq sessiyalar yo‘q.',
  noUpcomingBookings: 'Rejalashtirilgan darslar yo‘q',
  noPastBookings: 'O‘tgan darslar yo‘q',
  noCancelledBookings: 'Bekor qilingan darslar yo‘q',
  slotBookedCount: (count: number, cap: number) => `${count} / ${cap} band`,
  slotStatusAvailable: 'Ochiq',
  slotStatusAlmostFull: 'Deyarli to‘lgan',
  slotStatusFull: 'To‘lgan',
  slotStatusClosed: 'Yopiq',
  slotStatusClash: 'Guruh darsi bilan to‘qnashuv',
  confirmSession: 'Sessiyani tasdiqlash',
  confirmBookingButton: 'Yozilishni tasdiqlash',
  rescheduleTitle: 'Vaqtni o‘zgartirish',
  rescheduleConfirm: 'O‘ZGARTIRISH',
  rescheduleSuccess: 'Dars vaqti muvaffaqiyatli o‘zgartirildi',
  sameDayCutoffNotice: (time: string) => `Bugungi darslarni bekor qilish ${time} da yopiladi`,
  todayDisabledNotice: 'Bugunga yozilish yopiq (kamida 1 kun oldin)',
  holidayNotice: 'Maktab dam olish kuni',
  filterAll: 'Barchasi',
  filterUpcoming: 'Kelgusi',
  filterPast: 'O‘tgan',
  filterCancelled: 'Bekor qilingan',
  purposeLabel: 'Dars maqsadi',

  // ── Progress ───────────────────────────────────────────
  progressSubtitle: 'Mavzular, imtihonlar va ishlaringiz',
  curriculumHeader: "O'QUV REJASI",
  examsHeader: 'IMTIHONLAR',
  supportHeader: "QO'SHIMCHA DARSLAR",
  topicsProgress: (done: number, total: number) => `${done} / ${total} mavzu tugallandi`,
  topicCompleted: 'Tugallangan',
  topicInProgress: 'Jarayonda',
  topicNotStarted: 'Boshlanmagan',
  examPass: "O'tdi",
  examConditional: 'Shartli',
  examFail: "O'tmadi",
  examViewScan: "Ishni ko'rish",
  examNoScan: "Skan yo'q",
  examScoreUnit: 'ball',
  emptyTopicsTitle: "O'quv rejasi hali tuzilmagan",
  emptyExamsTitle: 'Imtihonlar hali topshirilmagan',

  // ── Profile ────────────────────────────────────────────
  contactHeader: 'ALOQA',
  phoneLabel: 'Telefon',
  phoneSheetTitle: 'Telefon raqam',
  phoneNote: "Maktab shu raqamga qo'ng'iroq qiladi. O'zgartirish qayd etiladi.",
  save: 'SAQLASH',
  saved: "O'zgarishlar saqlandi",
  settingsHeader: 'SOZLAMALAR',
  notificationsRow: 'Bildirishnomalar',
  languageRow: 'Til',
  darkModeRow: 'Tungi rejim',
  pinRow: 'PIN kod',
  schoolHeader: "MAKTAB MA'LUMOTLARI",
  schoolNote: "Bu ma'lumotlarni faqat administrator o'zgartira oladi.",
  levelLabel: 'Daraja',
  groupLabel: 'Guruh',
  statusLabel: 'Status',
  teacherLabel: "O'qituvchi",
  loginLabel: 'Login',
  logout: 'CHIQISH',
  photoUpload: 'Rasm yuklash',
  photoCamera: 'Kameradan olish',
  photoDelete: "Rasmni o'chirish",
  cancel: 'Bekor qilish',
  close: 'Yopish',
  childrenHeader: 'FARZANDLARIM',
  notifPrefsHeader: 'BILDIRISHNOMALAR',
  notifPrefAbsent: 'Darsga kelmadi',
  notifPrefHw: 'Uy vazifasi bajarilmadi',
  notifPrefDue: "To'lov eslatmasi",
  notifPrefPaid: "To'lov qabul qilindi",
  notifPrefExam: 'Imtihon natijasi',
  notifPrefNote: "Kuniga 3 tadan ortiq xabar yubormaymiz.",

  // ── Parent · Today ─────────────────────────────────────
  parentPresent: (name: string) => `${name} darsga keldi`,
  parentLate: (name: string) => `${name} kech qoldi`,
  parentAbsent: (name: string) => `${name} darsga kelmadi`,
  parentUnmarked: (name: string) => `${name} uchun davomat belgilanmagan`,
  debtTitle: (sum: string) => `${sum} so'm qarz`,
  debtCta: "TO'LOVLARNI KO'RISH",
  debtAllChildren: (sum: string) => `Barcha farzandlar bo'yicha: ${sum} so'm`,
  allPaid: "Hammasi to'langan",

  // ── Payments ───────────────────────────────────────────
  balanceCaption: 'QARZ',
  monthsHeader: 'OYLAR',
  paid: "To'langan",
  writtenOff: 'Hisobdan chiqarilgan',
  debtPill: (sum: string) => `${sum} qarz`,
  charged: 'Hisoblandi',
  paidRow: "To'landi",
  remainder: 'Qoldiq',
  receiptsHeader: 'KVITANSIYALAR',
  receiptVoided: 'Bekor qilingan',
  chequeGiven: "Qog'oz chek berilgan",
  paymentsFooter: "Noto'g'ri ko'ringan narsa bo'lsa, administratorga murojaat qiling — qog'oz cheklar ularda.",
  emptyChargesTitle: "Hisoblangan to'lovlar yo'q",
  currency: "so'm",
  receiptTo: 'Kimga',
  receiptId: 'ID',
  receiptMonth: 'Oy',
  receiptMethod: 'Usul',
  receiptTakenBy: 'Qabul qildi',
  receiptNo: 'Kvitansiya №',
  receiptShare: 'ULASHISH',
  receiptPdf: 'PDF',
  receiptVoidedBanner: 'Bu kvitansiya bekor qilingan',
  shared: 'Kvitansiya ulashildi',

  // ── Attendance (parent) ────────────────────────────────
  legendPresent: 'Keldi',
  legendLate: 'Kech',
  legendAbsent: 'Kelmadi',

  // ── Game (Arena) ───────────────────────────────────────
  tabGame: "O'yin",
  arenaSubtitle: 'Har kuni 5 daqiqa — katta natija',
  arenaLevel: (n: number) => `${n}-daraja`,
  arenaXp: (has: number, need: number) => `${has} / ${need} XP`,
  questsHeader: 'KUNLIK VAZIFALAR',
  unitHeader: (n: number) => `${n}-BO'LIM`,
  unitProgress: (done: number, total: number) => `${done}/${total}`,
  startLesson: 'BOSHLASH',
  levelLocked: 'Avval oldingi darajani tugating',
  leagueHeader: 'LIGA',
  leagueName: 'Kumush liga',
  leagueSub: 'Haftalik XP reytingi',
  leagueYou: 'Siz',
  leaguePromoZone: "O'TISH ZONASI — Oltin liga",
  leagueDemoteZone: 'TUSHISH ZONASI — Bronza',
  leagueEnds: 'Yakshanba 24:00 da yakunlanadi',
  leaguePlace: (n: number) => `${n}-o'rin`,
  tierBronze: 'Bronza',
  tierSilver: 'Kumush',
  tierGold: 'Oltin',
  tierDiamond: 'Olmos',
  shopTitle: "Do'kon",
  shopRowTitle: "Do'kon",
  shopRowSub: "Tangalarni sovg'alarga almashtiring",
  shopVouchers: 'KUPONLAR',
  shopMerch: 'PHOENIX MERCH',
  shopBoosts: 'KUCHAYTIRGICHLAR',
  shopBalance: 'SIZNING TANGALARINGIZ',
  buy: 'OLISH',
  bought: (name: string) => `${name} — sotib olindi ✓`,
  notEnoughCoins: 'Tangalar yetarli emas',
  energyIsFull: "Energiya allaqachon to'la",
  popularPill: 'TOP',
  coinsUnit: 'tanga',
  gameLockPill: "To'lov kutilmoqda",
  gameLockTitle: "O'yin vaqtincha yopiq",
  gameLockBody: "Oylik to'lov hali qabul qilinmadi. To'lov amalga oshirilgach, o'yin, do'kon va arena qayta ochiladi.",
  gameLockFoot: "To'lov ota-onangiz ilovasidagi «To'lovlar» bo'limida amalga oshiriladi.",
  playCheck: 'TEKSHIRISH',
  playContinue: 'DAVOM ETISH',
  playCorrect: "To'g'ri!",
  playWrong: "Noto'g'ri",
  playAnswerWas: (a: string) => `To'g'ri javob: ${a}`,
  playCombo: (n: number) => `${n} ta ketma-ket`,
  playQuestionOf: (i: number, n: number) => `${i}-savol / ${n}`,
  playResultsGreat: 'Ajoyib ish!',
  playResultsOk: 'Yaxshi urinish!',
  playXp: 'XP',
  playCoins: 'Tangalar',
  playAccuracy: 'Aniqlik',
  playNoEnergyTitle: 'Energiya tugadi',
  playNoEnergyBody: "Ertaga qayta to'ladi — yoki do'kondan darhol to'ldiring.",
  playFinish: 'YAKUNLASH',
  playPlusXp: (n: number) => `+${n} XP`,

  // ── Game hub ───────────────────────────────────────────
  catAll: 'Hammasi',
  catPath: 'Asosiy',
  catBattle: 'Arena',
  catSpeed: 'Sprint',
  catDaily: 'Vazifalar',
  catPractice: 'Amaliyot',
  catLife: 'Amaliy',
  battleHeroCaption: 'JONLI BELLASHUV',
  battleHeroTitle: 'Matematik jang',
  battleHeroBody: "10 o'yinchi · 5 savol · eng tezi yutadi",
  battleHeroCta: 'ARENAGA KIRISH',
  battleStats: (w: number, p: number) => `${w} g'alaba · ${p} o'yin`,
  dailyTitle: 'Kunlik challenge',
  dailyBody: '5 savol · darajangizga mos · seriya bonusi',
  dailyBonus: (n: number) => `Seriya bonusi: +${n}`,
  dailyDone: 'Bugungi challenge bajarildi',
  doneLabel: 'Bajarildi',
  sprintTitle: 'Mental sprint',
  sprintBody: '60 soniyada maksimal misol',
  sprintBest: (n: number) => `Rekord: ${n}`,
  sprintGo: 'BOSHLASH',
  sprintScore: 'Natija',
  sprintNewRecord: 'Yangi rekord!',
  sprintTimeUp: 'Vaqt tugadi',
  reviewTitle: 'Aqlli takrorlash',
  reviewBody: 'Zaif mavzular va imtihon xatolaridan tuzilgan',
  reviewSource: "Kasrlar · O'nli kasrlar",
  lifeTitle: 'Hayotiy matematika',
  lifeBody: 'Foizlar, chegirma, kredit — amaliy hisob-kitob',
  lifeMeta: (n: number) => `${n} masala`,
  tournamentCta: "Ro'yxatga yozilish",
  tournamentJoined: "Turnirga yozildingiz ✓",
  tournamentSoon: (d: string) => `${d} · markazda jonli final`,
  allUnitsRow: "Barcha bo'limlar",
  unitsScreenTitle: "O'quv rejasi",

  // ── Journey ────────────────────────────────────────────
  topicCaption: (n: number) => `MATEMATIKA · ${n}-MAVZU`,
  topicGamesOf: (a: number, b: number) => `${a}/${b} o'yin`,
  topicMastery: (p: number) => `${p}% o'zlashtirildi`,
  nextTopicCaption: 'KEYINGI MAVZU',
  nextTopicLock: 'Boss jangini yutgach ochiladi',
  nextTopicReward: (n: number) => `Ochilganda: +${n} tanga`,
  pathBattleTitle: 'Jang',
  pathBattleSub: '10 kishilik jonli bellashuv',
  pathBattleLocked: 'Boss jangidan keyin ochiladi',
  topicDoneTitle: 'Mavzu yakunlandi!',
  topicUnlockedCaption: 'YANGI MAVZU OCHILDI',
  levelUpTitle: 'Yangi daraja!',
  tapToContinue: 'Davom etish uchun bosing',
  soundOnLabel: "Ovozni o'chirish",
  soundOffLabel: 'Ovozni yoqish',
  allTopicsLink: 'Barcha mavzular',
  energyInfo: (n: number, max: number) => `Energiya: ${n}/${max}. Har bir xato javobda 1 taga kamayadi, ertaga yana to'ladi.`,
  streakInfo: (n: number) => `Siz ${n} kundan beri har kuni shug'ullanyapsiz. Bugun ham o'ynasangiz — olov o'chmaydi!`,
  streakToast: (n: number) => `Ajoyib! Ketma-ket ${n}-kun`,
  streakTitle: (n: number) => `${n} kun ketma-ket!`,
  streakBody: "Har kuni kamida 1 ta o'yin o'ynang",

  // ── Battle ─────────────────────────────────────────────
  battleTitle: 'Matematik jang',
  battleModeQuestion: 'Rejimni tanlang',
  battleSameTitle: "O'z darajangizda",
  battleSameBody: "Raqiblar ham, savollar ham sizning darajangizga mos tanlanadi.",
  battleMixedTitle: 'Aralash daraja',
  battleMixedBody: "Har xil darajadagi o'quvchilar bilan o'ynaysiz. Savollar oson ham, qiyin ham bo'lishi mumkin.",
  battleFind: 'RAQIB QIDIRISH',
  battleYourLevel: 'Sizning darajangiz',
  battleSearching: 'Event qidirilmoqda…',
  battleFoundEvent: (n: number) => `Ochiq event topildi · №${n}`,
  battleCreatedEvent: (n: number) => `Yangi event yaratildi · №${n} — siz birinchisiz`,
  battleFullSkip: "Topilgan event to'la — boshqasi qidirilmoqda…",
  battlePlayers: (a: number, b: number) => `${a}/${b}`,
  battleWaiting: 'Kutilmoqda',
  battleAlmost: "Deyarli to'ldi",
  battleFullPill: "To'ldi",
  battleLocked: "Event to'ldi — yangi o'yinchilar qabul qilinmaydi",
  battleNeedMore: (n: number) => `Yana ${n} o'yinchi kutilmoqda…`,
  battleStartsSoon: 'Boshlanishi: tez orada',
  battleStartsVerySoon: 'Boshlanishi: juda yaqin',
  battleLeft: (name: string) => `${name} chiqib ketdi`,
  battleJoined: (name: string) => `${name} qo'shildi`,
  battleLeave: 'Chiqish',
  battleGetReady: 'Tayyorlaning!',
  battleStart: 'START',
  battleYou: 'Siz',
  battleRank: (n: number) => `${n}-o'rin`,
  battleLive: 'JONLI',
  battleResultsTitle: 'Jang yakunlandi',
  battlePlayAgain: 'YANA JANG',
  battleExit: 'CHIQISH',
  battleScoreUnit: 'ball',
  levelShort: (n: number) => `L${n}`,

  // ── Mission ────────────────────────────────────────────
  missionHeader: 'Haftalik missiya',
  missionDaysLeft: (n: number) => `${n} kun qoldi`,
  missionProgress: (a: number, b: number) => `${a}/${b}`,
  unitsHeader: "Bo'limlar",
  unitLessonsOf: (a: number, b: number) => `${a}/${b} dars`,

  // ── Shop (e-commerce) ──────────────────────────────────
  shopFeatured: 'HAFTA MAHSULOTI',
  shopCollection: 'Mening kolleksiyam',
  shopGet: 'OLISH',
  shopOwned: 'Sizniki',
  shopProcessing: 'Rasmiylashtirilmoqda…',
  shopSuccessTitle: 'Mukofot ochildi',
  shopSuccessBody: (name: string) => `${name} kolleksiyangizga qo'shildi`,
  shopNeedMore: (n: string) => `Yana ${n} tanga kerak`,
  shopEarnHint: "Tangalarni o'yinlarda va kunlik challenge'da yig'asiz",
  shopBalanceOf: (a: string, b: string) => `${a} / ${b}`,
  shopPriceCoins: (p: string) => `${p} tanga`,

  // ── Notifications ──────────────────────────────────────
  notificationsTitle: 'Bildirishnomalar',
  markAllRead: "Hammasini o'qildi",
  notifNewHeader: 'YANGI',
  notifOldHeader: 'OLDINGI',
  emptyNotifTitle: "Bildirishnomalar yo'q",
  emptyNotifBody: "Yangi xabarlar shu yerda ko'rinadi.",

  // ── Language ───────────────────────────────────────────
  langTitle: 'Til',
  langUz: "O'zbekcha",
  langRu: 'Русский',
  langEn: 'English',

  // ── Global states ──────────────────────────────────────
  errorTitle: "Ma'lumot yuklanmadi",
  errorBody: "Internetni tekshirib, qayta urinib ko'ring.",
  errorRetry: 'QAYTA URINISH',
  offline: (when: string) => `Internet yo'q · Oxirgi ma'lumot: ${when}`,
  offlineWhen: '12-avgust, 14:30',
  back: 'Orqaga',

  // ── Avatar studio ──────────────────────────────────────
  avatarStudioTitle: 'Avatar yarating',
  avatarStudioSubtitle: "O'zingizniki qiling",
  avatarSave: 'Saqlash',
  avatarSavedShort: 'Saqlandi',
  avatarSaved: 'Avatar saqlandi',
  avatarSaveError: 'Avatar saqlanmadi',
  avatarSaveErrorBody: "Qurilma xotirasiga yozib bo'lmadi. Qayta urinib ko'ring.",
  avatarRetry: 'Qayta urinish',
  avatarKeepEditing: 'Davom etish',
  avatarDiscardTitle: "O'zgarishlar bekor qilinsinmi?",
  avatarDiscardBody: "Saqlanmagan o'zgarishlar yo'qoladi.",
  avatarDiscard: 'Saqlamasdan chiqish',
  avatarReset: 'Boshidan',
  avatarResetTitle: 'Boshidan boshlaysizmi?',
  avatarResetBody: 'Barcha tanlovlar standart avatarga qaytadi.',
  avatarResetConfirm: 'Qaytarish',
  avatarClose: 'Yopish',
  avatarEditLabel: 'Avatarni tahrirlash',
  avatarCatSkin: 'Teri',
  avatarCatFace: 'Yuz',
  avatarCatEyes: "Ko'zlar",
  avatarCatBrows: 'Qoshlar',
  avatarCatMouth: "Og'iz",
  avatarCatHair: 'Soch',
  avatarCatHeadwear: 'Bosh kiyim',
  avatarCatClothing: 'Kiyim',
  avatarCatAccessories: 'Aksessuar',
  avatarCatBackground: 'Fon',
  avatarCatHijab: 'Hijob',
  avatarTypeTitle: 'Avatar kim uchun?',
  avatarTypeSubtitle: "Keyin hammasini o'zgartira olasiz",
  avatarBoy: "O'g'il bola",
  avatarGirl: 'Qiz bola',
  avatarSwitchTitle: 'Avatar turi almashtirilsinmi?',
  avatarSwitchBody: "Hozirgi bezaklar yangi tur uchun standart ko'rinishga almashtiriladi.",
  avatarSwitchConfirm: 'Almashtirish',
  avatarSwitchLabel: 'Avatar turini almashtirish',
  avatarNone: "Yo'q",
  avatarColorHeader: 'Rang',
  avatarStyleHeader: 'Uslub',
  avatarOptionLabel: (n: number) => `${n}-variant`,

  // ── Dev tool ───────────────────────────────────────────
  devTitle: 'PROTOTYPE CONTROLS',
  devTheme: 'Theme',
  devRole: 'Role',
  devLight: 'Light',
  devDark: 'Dark',
  devStudent: 'Student',
  devParent: 'Parent',
  devState: 'Data state',
  devGame: 'Game payment',
  devPaid: 'Paid',
  devUnpaid: 'Unpaid',
  devFull: 'Full',
  devLoading: 'Loading',
  devEmpty: 'Empty',
  devError: 'Error',
  devOffline: 'Offline',
  devRestart: 'Restart auth',

  // ── Header ─────────────────────────────────────────────
  profileOpenLabel: 'Profilni ochish',

  // ── Ranking ────────────────────────────────────────────
  rankingTitle: 'Reyting',
  rankingSubtitle: 'Akademik ko‘rsatkich bo‘yicha',
  rankScopeLevel: 'Mening darajam',
  rankScopeAll: 'Barcha darajalar',
  rankModePerformance: 'Ko‘rsatkich',
  rankModeImprovement: 'O‘sish',
  rankTopStudents: 'Eng yaxshi o‘quvchilar',
  rankYourPosition: 'Sizning o‘rningiz',
  rankScore: 'Akademik ball',
  rankMovementUp: (n: number) => `${n} o‘rin ko‘tarildingiz`,
  rankMovementDown: (n: number) => `${n} o‘rin tushdingiz`,
  rankMovementNone: 'O‘rin o‘zgarmadi',
  rankNoHistory: 'Oldingi oy bilan taqqoslash ma’lumoti yo‘q',
  rankHowCalculated: 'Ball qanday hisoblanadi?',
  rankFormulaIntro: 'Ball bir nechta akademik ko‘rsatkichdan yig‘iladi:',
  rankComponentMastery: 'O‘zlashtirish',
  rankComponentExams: 'Imtihonlar',
  rankComponentHomework: 'Uy vazifasi',
  rankComponentCurriculum: 'Dastur',
  rankComponentConsistency: 'Muntazamlik',
  rankHowToMoveUp: 'Yuqoriga ko‘tarilish uchun',
  rankPointsBehind: (points: string, rank: number) => `#${rank} o‘rindan ${points} ball orqadasiz`,
  rankAdviceUnit: (unit: string) => `${unit} bo‘yicha o‘zlashtirishni oshiring`,
  rankAdviceHomework: 'Uy vazifalarini to‘liq bajaring',
  rankAdviceExam: 'Keyingi imtihonga puxta tayyorlaning',
  rankEmptyTitle: 'Reyting tayyorlanmoqda',
  rankEmptyBody: 'Reytingda paydo bo‘lish uchun yana bir nechta baholash kerak.',
  rankLevel: (level: string) => `${level} daraja`,

  // ── Progress ───────────────────────────────────────────
  pgSummary: (name: string, level: string) => `${name} hozir ${level} darajada`,
  pgGoalHeader: 'MAQSADIM',
  pgNow: 'Hozir',
  pgTarget: 'Maqsad',
  pgTargetDate: (date: string) => `Muddat: ${date}`,
  pgReadinessHeader: 'TAYYORGARLIK',
  pgReadinessBasis: (done: number, total: number) =>
  `${total} ta mavzudan ${done} tasi maqsad darajasida ko‘rsatilgan`,
  pgReadinessUnknown: 'Tayyorgarlikni baholash uchun baho ma’lumoti yetarli emas',
  readinessStrong: 'Kuchli tayyorgarlik',
  readinessOnTrack: 'Reja bo‘yicha',
  readinessNeedsWork: 'Ishlash kerak',
  bandFoundation: 'Poydevor kerak',
  bandDeveloping: 'Rivojlanmoqda',
  bandStrong: 'Kuchli',
  bandMastered: 'O‘zlashtirilgan',
  pgStrengths: 'KUCHLI TOMONLAR',
  pgWeak: 'E’TIBOR TALAB QILADI',
  pgOverall: 'Umumiy progress',
  pgCompletedOf: (done: number, total: number) => `${total} ta mavzudan ${done} tasi tugallandi`,
  pgMetricTopics: 'Mavzular',
  pgMetricExams: 'Imtihon o‘rtachasi',
  pgExamLatest: 'Oxirgi:',
  pgExamBest: 'eng yaxshi:',
  pgActivitySince: (date: string) => `${date} dan beri`,
  pgActivityAttended: (a: number, b: number) => `${b} darsdan ${a} tasida qatnashdi`,
  pgRecentHeader: 'SO‘NGGI HARAKATLAR',
  pgActAttended: 'Darsga keldi',
  pgActMissed: 'Darsni o‘tkazib yubordi',
  pgActHomework: 'Uy vazifasini bajardi',
  pgActExam: (score: string) => `Imtihon topshirdi — ${score} ball`,
  pgMilestoneHeader: 'KEYINGI BOSQICH',
  pgTopicsLeft: (n: number) => `${n} ta mavzu qoldi`,
  pgContinue: 'Davom etish',
  pgLevelsHeader: 'DARAJALAR',

  // ── Chat ───────────────────────────────────────────────
  chatTitle: 'Suhbatlar',
  chatSearch: 'Suhbat qidirish',
  chatSectionLearning: 'O‘QUV',
  chatSectionSupport: 'YORDAM',
  chatSectionAdmin: 'MA’MURIYAT',
  chatOnline: 'Onlayn',
  chatYou: 'Siz',
  chatComposer: 'Xabar yozing',
  chatSendLabel: 'Yuborish',
  chatAttachLabel: 'Fayl biriktirish',
  chatAttachSoon: 'Fayl biriktirish keyingi versiyada',
  chatDayToday: 'Bugun',
  chatDayYesterday: 'Kecha',
  chatDayEarlier: 'Avvalroq',
  chatEmptyTitle: 'Suhbat yo‘q',
  chatEmptyBody: 'Guruhingiz va yordam xizmati shu yerda ko‘rinadi.',
  chatThreadEmptyTitle: 'Suhbatni boshlang',
  chatThreadEmptyBody: 'Bugungi dars bo‘yicha savol bering.',
  chatSupportQuick: 'Nima bo‘yicha yordam kerak?',
  chatTopicPayment: 'To‘lov',
  chatTopicTechnical: 'Texnik muammo',
  chatTopicAccount: 'Hisob',
  chatTopicCourse: 'Kurs',
  chatSearchEmpty: 'Hech narsa topilmadi',

  // ── Practice (inside Lessons) ──────────────────────────
  practiceHeader: 'MASHQ REJASI',
  practiceIntro: 'Zaif mavzular bo‘yicha shu haftalik reja',
  practiceEmpty: 'Hozircha mashq talab qiladigan mavzu yo‘q',

  // ── Lessons · curriculum ───────────────────────────────
  lsSegCurriculum: 'Dastur',
  lsSegAttendance: 'Davomat',
  lsCompletedOf: (done: number, total: number) => `${done} / ${total} mavzu tugallandi`,
  lsStateCompleted: 'Tugallangan',
  lsStateCurrent: 'Joriy',
  lsStateLocked: 'Yopiq',
  lsTopicsShort: (done: number, total: number) => `${done}/${total} mavzu`,
  lsLockedHint: (n: number) => `Ochilishi uchun yana ${n} ta mavzu`,
  lsLockedToast: 'Bu mavzu hali ochilmagan',
  lsContinueHere: 'Shu yerdan davom eting',
  lsLesson: 'Dars matni',
  lsWatched: 'Ko‘rilgan',
  lsNotWatched: 'Ko‘rilmagan',
  lsExam: 'Imtihon',
  lsEmptyTitle: 'Dastur biriktirilmagan',
  lsEmptyBody: 'Guruhingizga o‘quv dasturi biriktirilgach shu yerda ko‘rinadi.',
  lsExpandLevel: 'Darajani ochish',
  lsExpandModule: 'Modulni ochish',
  lsStepLearn: 'Ko‘rish',
  lsStepPractice: 'Mashq',
  lsPracticeHint: 'Amaliy mashqlar',
  lsHomeworkNone: 'Berilmagan',
  lsAvailable: 'Mavjud',
  lsWatchVideo: 'Videoni ko‘rish',
  lsRewatch: 'Qayta ko‘rish',
  lsVideoMissing: 'Video hali yuklanmagan',
  lsVideoMissingBody: 'Yuklangach shu yerda ochiladi. Savolingiz bo‘lsa o‘qituvchiga yozing.',
  lsAttClasses: 'Dars',
  lsAttPresent: 'Keldi',
  lsAttRate: 'Davomat',
  lsAttEmpty: 'Bu oyda dars bo‘lmagan',
  lsAttHint: 'Kunni tanlang yoki oyni surib ko‘ring',
  lsDoneBadge: 'Yakunlandi',
  lsExamResult: 'Imtihon natijasi',
  lsTopicsHeader: 'Mavzular',
  lsPracticeLocked: 'Videoni ko‘rgach ochiladi',
  lsLevelLockedHint: 'Avval joriy darajani yakunlang',
  pgActivityHeader: 'FAOLLIK',
  pgLessonsTaken: 'Dars o‘tildi',
  pgVideosWatched: 'Video ko‘rildi',
  pgDuration: (h: number, m: number) => h > 0 ? `${h} soat ${m} daq` : `${m} daqiqa`,
  soundRow: 'Ovoz effektlari'
};

export type Strings = typeof uz;

const ru: Strings = {
  monthsFull: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
  monthsGen: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
  weekdaysShort: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  weekdaysLong: ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'],

  brand: 'Phoenix Math School',
  version: 'Phoenix Math School · v1.0',

  authWelcome: 'Добро пожаловать',
  authSubtitle: 'Войдите в свой аккаунт',
  authIdLabel: 'ID номер',
  authIdPlaceholder: '01234',
  authPasswordLabel: 'Пароль',
  authPasswordPlaceholder: '••••••••',
  authSignIn: 'ВОЙТИ',
  authForgot: 'Забыли пароль? Обратитесь к администратору.',
  authError: 'Неверный ID или пароль. Попробуйте ещё раз.',
  authShowPassword: 'Показать пароль',
  authHidePassword: 'Скрыть пароль',

  pwTitle: 'Установите новый пароль',
  pwBody: 'Первый пароль был временным. Придумайте пароль, известный только вам.',
  pwNew: 'Новый пароль',
  pwRepeat: 'Повторите',
  pwRule8: 'Минимум 8 символов',
  pwRuleDigit: 'Минимум 1 цифра',
  pwRuleMatch: 'Пароли совпадают',
  pwSave: 'СОХРАНИТЬ',

  bioTitle: 'Включить быстрый вход?',
  bioBody: 'Чтобы не вводить пароль каждый раз.',
  bioFace: 'ВКЛЮЧИТЬ FACE ID',
  bioPin: 'Установить 4-значный PIN',
  bioSkip: 'Не сейчас',

  pinTitle: 'Введите PIN-код',
  pinWrong: 'Неверный PIN-код',
  pinDelete: 'Стереть',
  pinFaceId: 'Face ID',

  tabToday: 'Сегодня',
  tabLessons: 'Уроки',
  tabBookings: 'Запись',
  tabProgress: 'Прогресс',
  tabProfile: 'Профиль',
  tabAttendance: 'Посещения',
  tabPayments: 'Платежи',

  todayGreeting: (name: string) => `Привет, ${name}`,
  todayLessonCaption: 'УРОК СЕГОДНЯ',
  todayNoLesson: 'Сегодня урока нет',
  todayNextLesson: 'Следующий урок: завтра в 14:00',
  todayAllClear: 'Всё в порядке 👍',
  todayAllClearBody: 'На сегодня невыполненных дел нет.',
  nextBookingHeader: 'СЛЕДУЮЩАЯ ЗАПИСЬ',
  lastExamHeader: 'ПОСЛЕДНИЙ ЭКЗАМЕН',
  weakPointBody: 'Учитель считает, что по этой теме нужен ещё один урок.',
  weakPointCta: 'ЗАПИСАТЬСЯ',
  finishHeader: 'НУЖНО ЗАВЕРШИТЬ',

  statAttendance: 'Посещение',
  statHomework: 'Домашка',
  statTopics: 'Темы',
  statLessons: 'Уроки',
  statPresent: 'Пришёл',
  statPresentParent: 'Пришёл',

  lessonsSubtitle: 'Каждый урок и как он прошёл',
  segAll: 'Все',
  segAbsent: 'Пропуски',
  segHomework: 'Домашка',
  lessonAttendance: 'Посещение',
  lessonHomework: 'Домашняя работа',
  lessonConspect: 'Конспект',
  lessonEngagement: 'Активность',
  emptyLessonsTitle: 'Уроки ещё не отмечены',
  emptyLessonsBody: 'Появятся здесь после отметки посещаемости.',

  present: 'Пришёл',
  late: 'Опоздал',
  absent: 'Не пришёл',
  unmarked: 'Не отмечено',
  hwDone: 'Выполнено',
  hwNot: 'Не выполнено',
  hwPartial: 'Частично',
  conspectFull: 'Полный',
  conspectPartial: 'Частично',
  engHigh: 'Высокая',
  engMedium: 'Средняя',
  engLow: 'Низкая',

  bookingsSubtitle: 'Забронируйте время для дополнительного урока',
  quotaLine: (left: number, limit: number) => `На этой неделе осталось ${left} из ${limit}`,
  quotaSpent: 'Лимит на эту неделю исчерпан. Запись снова откроется в понедельник.',
  newBooking: 'НОВАЯ ЗАПИСЬ',
  upcomingHeader: 'ПРЕДСТОЯЩИЕ',
  pastHeader: 'ПРОШЕДШИЕ',
  bookingAttended: 'Посетил',
  bookingMissed: 'Не пришёл',
  bookingCancelled: 'Отменено',
  bookingNeedsAnother: 'Нужен ещё урок',
  bookingLocked: 'Изменение закрыто в 12:00.',
  swipeCancel: 'Отменить',
  emptyBookingsTitle: 'Записей пока нет',
  emptyBookingsBody: 'Забронируйте время для дополнительного урока.',

  sheetNewBooking: 'Новая запись',
  stepDate: 'ДАТА',
  stepTime: 'ВРЕМЯ',
  stepPurpose: 'ЦЕЛЬ',
  purposePlaceholder: 'например: Дроби — общий знаменатель',
  purposeHint: 'Минимум 3 символа.',
  confirm: 'ПОДТВЕРДИТЬ',
  bookingConfirmed: 'Запись подтверждена',
  cancelTitle: 'Отменить запись?',
  cancelReasonLabel: 'Причина (минимум 10 символов)',
  cancelReasonPlaceholder: 'Почему вы отменяете? (минимум 10 символов)',
  cancelReasonHint: 'От 10 до 300 символов.',
  cancelReasonMin: 'Причина должна содержать минимум 10 символов',
  cancelConfirm: 'ОТМЕНИТЬ',
  cancelBack: 'Назад',
  cancelKeep: 'Оставить запись',
  bookingCancelledToast: 'Запись отменена',

  bookingTabBook: 'Запись',
  bookingTabMine: 'Мои записи',
  weeklyUsageTitle: 'Недельные уроки',
  weeklyUsageRemaining: (rem: number) => `Осталось: ${rem}`,
  weeklyUsageLimitReached: 'Лимит на неделю исчерпан',
  sessionsAvailable: 'Доступные сессии',
  noSlotsForDate: 'Нет доступных сессий на эту дату.',
  noUpcomingBookings: 'Нет предстоящих занятий',
  noPastBookings: 'Нет прошедших занятий',
  noCancelledBookings: 'Нет отмененных занятий',
  slotBookedCount: (count: number, cap: number) => `${count} / ${cap} занято`,
  slotStatusAvailable: 'Доступно',
  slotStatusAlmostFull: 'Почти заполнено',
  slotStatusFull: 'Заполнено',
  slotStatusClosed: 'Закрыто',
  slotStatusClash: 'Конфликт с групповым уроком',
  confirmSession: 'Подтверждение сессии',
  confirmBookingButton: 'Подтвердить запись',
  rescheduleTitle: 'Перенести запись',
  rescheduleConfirm: 'ПЕРЕНЕСТИ',
  rescheduleSuccess: 'Запись успешно перенесена',
  sameDayCutoffNotice: (time: string) => `Отмена занятий на сегодня закрывается в ${time}`,
  todayDisabledNotice: 'Запись на сегодня недоступна (минимум за 1 день)',
  holidayNotice: 'Праздничный день в школе',
  filterAll: 'Все',
  filterUpcoming: 'Предстоящие',
  filterPast: 'Прошедшие',
  filterCancelled: 'Отмененные',
  purposeLabel: 'Цель занятия',

  progressSubtitle: 'Темы, экзамены и ваши работы',
  curriculumHeader: 'УЧЕБНЫЙ ПЛАН',
  examsHeader: 'ЭКЗАМЕНЫ',
  supportHeader: 'ДОП. УРОКИ',
  topicsProgress: (done: number, total: number) => `Пройдено ${done} / ${total} тем`,
  topicCompleted: 'Завершено',
  topicInProgress: 'В процессе',
  topicNotStarted: 'Не начато',
  examPass: 'Сдал',
  examConditional: 'Условно',
  examFail: 'Не сдал',
  examViewScan: 'Открыть работу',
  examNoScan: 'Нет скана',
  examScoreUnit: 'балл',
  emptyTopicsTitle: 'Учебный план ещё не составлен',
  emptyExamsTitle: 'Экзамены ещё не сдавались',

  contactHeader: 'КОНТАКТ',
  phoneLabel: 'Телефон',
  phoneSheetTitle: 'Номер телефона',
  phoneNote: 'Школа звонит на этот номер. Изменение фиксируется.',
  save: 'СОХРАНИТЬ',
  saved: 'Изменения сохранены',
  settingsHeader: 'НАСТРОЙКИ',
  notificationsRow: 'Уведомления',
  languageRow: 'Язык',
  darkModeRow: 'Тёмная тема',
  pinRow: 'PIN-код',
  schoolHeader: 'ДАННЫЕ ШКОЛЫ',
  schoolNote: 'Эти данные может изменить только администратор.',
  levelLabel: 'Уровень',
  groupLabel: 'Группа',
  statusLabel: 'Статус',
  teacherLabel: 'Учитель',
  loginLabel: 'Логин',
  logout: 'ВЫЙТИ',
  photoUpload: 'Загрузить фото',
  photoCamera: 'Сделать снимок',
  photoDelete: 'Удалить фото',
  cancel: 'Отмена',
  close: 'Закрыть',
  childrenHeader: 'МОИ ДЕТИ',
  notifPrefsHeader: 'УВЕДОМЛЕНИЯ',
  notifPrefAbsent: 'Не пришёл на урок',
  notifPrefHw: 'Домашка не выполнена',
  notifPrefDue: 'Напоминание об оплате',
  notifPrefPaid: 'Платёж получен',
  notifPrefExam: 'Результат экзамена',
  notifPrefNote: 'Не более 3 сообщений в день.',

  parentPresent: (name: string) => `${name} пришёл на урок`,
  parentLate: (name: string) => `${name} опоздал`,
  parentAbsent: (name: string) => `${name} не пришёл на урок`,
  parentUnmarked: (name: string) => `Посещение для ${name} не отмечено`,
  debtTitle: (sum: string) => `Долг ${sum} сум`,
  debtCta: 'К ПЛАТЕЖАМ',
  debtAllChildren: (sum: string) => `По всем детям: ${sum} сум`,
  allPaid: 'Всё оплачено',

  balanceCaption: 'ДОЛГ',
  monthsHeader: 'МЕСЯЦЫ',
  paid: 'Оплачено',
  writtenOff: 'Списано',
  debtPill: (sum: string) => `долг ${sum}`,
  charged: 'Начислено',
  paidRow: 'Оплачено',
  remainder: 'Остаток',
  receiptsHeader: 'КВИТАНЦИИ',
  receiptVoided: 'Аннулирована',
  chequeGiven: 'Выдан бумажный чек',
  paymentsFooter: 'Если что-то выглядит неверно, обратитесь к администратору — бумажные чеки у них.',
  emptyChargesTitle: 'Начислений нет',
  currency: 'сум',
  receiptTo: 'Кому',
  receiptId: 'ID',
  receiptMonth: 'Месяц',
  receiptMethod: 'Способ',
  receiptTakenBy: 'Принял',
  receiptNo: 'Квитанция №',
  receiptShare: 'ПОДЕЛИТЬСЯ',
  receiptPdf: 'PDF',
  receiptVoidedBanner: 'Эта квитанция аннулирована',
  shared: 'Квитанция отправлена',

  legendPresent: 'Пришёл',
  legendLate: 'Опоздал',
  legendAbsent: 'Не пришёл',

  tabGame: 'Игра',
  arenaSubtitle: '5 минут в день — большой результат',
  arenaLevel: (n: number) => `Уровень ${n}`,
  arenaXp: (has: number, need: number) => `${has} / ${need} XP`,
  questsHeader: 'ЗАДАНИЯ ДНЯ',
  unitHeader: (n: number) => `РАЗДЕЛ ${n}`,
  unitProgress: (done: number, total: number) => `${done}/${total}`,
  startLesson: 'СТАРТ',
  levelLocked: 'Сначала завершите предыдущий уровень',
  leagueHeader: 'ЛИГА',
  leagueName: 'Серебряная лига',
  leagueSub: 'Недельный рейтинг XP',
  leagueYou: 'Вы',
  leaguePromoZone: 'ЗОНА ПОВЫШЕНИЯ — Золотая лига',
  leagueDemoteZone: 'ЗОНА ВЫЛЕТА — Бронза',
  leagueEnds: 'Завершается в воскресенье в 24:00',
  leaguePlace: (n: number) => `${n}-е место`,
  tierBronze: 'Бронза',
  tierSilver: 'Серебро',
  tierGold: 'Золото',
  tierDiamond: 'Алмаз',
  shopTitle: 'Магазин',
  shopRowTitle: 'Магазин',
  shopRowSub: 'Обменивайте монеты на награды',
  shopVouchers: 'КУПОНЫ',
  shopMerch: 'PHOENIX MERCH',
  shopBoosts: 'УСИЛИТЕЛИ',
  shopBalance: 'ВАШИ МОНЕТЫ',
  buy: 'КУПИТЬ',
  bought: (name: string) => `${name} — куплено ✓`,
  notEnoughCoins: 'Недостаточно монет',
  energyIsFull: 'Энергия уже полная',
  popularPill: 'ТОП',
  coinsUnit: 'монет',
  gameLockPill: 'Ожидается оплата',
  gameLockTitle: 'Игра временно закрыта',
  gameLockBody: 'Ежемесячная оплата ещё не получена. После оплаты игра, магазин и арена снова откроются.',
  gameLockFoot: 'Оплата производится в разделе «Платежи» приложения родителей.',
  playCheck: 'ПРОВЕРИТЬ',
  playContinue: 'ПРОДОЛЖИТЬ',
  playCorrect: 'Верно!',
  playWrong: 'Неверно',
  playAnswerWas: (a: string) => `Правильный ответ: ${a}`,
  playCombo: (n: number) => `${n} подряд`,
  playQuestionOf: (i: number, n: number) => `Вопрос ${i} / ${n}`,
  playResultsGreat: 'Отличная работа!',
  playResultsOk: 'Хорошая попытка!',
  playXp: 'XP',
  playCoins: 'Монеты',
  playAccuracy: 'Точность',
  playNoEnergyTitle: 'Энергия закончилась',
  playNoEnergyBody: 'Восстановится завтра — или пополните в магазине.',
  playFinish: 'ЗАВЕРШИТЬ',
  playPlusXp: (n: number) => `+${n} XP`,

  catAll: 'Все',
  catPath: 'Главная',
  catBattle: 'Арена',
  catSpeed: 'Спринт',
  catDaily: 'Задания',
  catPractice: 'Практика',
  catLife: 'Практика',
  battleHeroCaption: 'ЖИВОЕ СОСТЯЗАНИЕ',
  battleHeroTitle: 'Математический батл',
  battleHeroBody: '10 игроков · 5 вопросов · побеждает быстрейший',
  battleHeroCta: 'НА АРЕНУ',
  battleStats: (w: number, p: number) => `${w} побед · ${p} игр`,
  dailyTitle: 'Ежедневный челлендж',
  dailyBody: '5 вопросов · по вашему уровню · бонус за серию',
  dailyBonus: (n: number) => `Бонус за серию: +${n}`,
  dailyDone: 'Челлендж на сегодня выполнен',
  doneLabel: 'Готово',
  sprintTitle: 'Ментальный спринт',
  sprintBody: 'Максимум примеров за 60 секунд',
  sprintBest: (n: number) => `Рекорд: ${n}`,
  sprintGo: 'СТАРТ',
  sprintScore: 'Результат',
  sprintNewRecord: 'Новый рекорд!',
  sprintTimeUp: 'Время вышло',
  reviewTitle: 'Умное повторение',
  reviewBody: 'Составлено из слабых тем и ошибок на экзаменах',
  reviewSource: 'Дроби · Десятичные дроби',
  lifeTitle: 'Математика жизни',
  lifeBody: 'Проценты, скидки, кредит — практический счёт',
  lifeMeta: (n: number) => `${n} задач`,
  tournamentCta: 'Записаться',
  tournamentJoined: 'Вы записаны на турнир ✓',
  tournamentSoon: (d: string) => `${d} · живой финал в центре`,
  allUnitsRow: 'Все разделы',
  unitsScreenTitle: 'Учебный план',

  topicCaption: (n: number) => `МАТЕМАТИКА · ТЕМА ${n}`,
  topicGamesOf: (a: number, b: number) => `${a}/${b} игр`,
  topicMastery: (p: number) => `Освоено ${p}%`,
  nextTopicCaption: 'СЛЕДУЮЩАЯ ТЕМА',
  nextTopicLock: 'Откроется после победы над боссом',
  nextTopicReward: (n: number) => `При открытии: +${n} монет`,
  pathBattleTitle: 'Батл',
  pathBattleSub: 'Живое состязание на 10 игроков',
  pathBattleLocked: 'Откроется после босса',
  topicDoneTitle: 'Тема завершена!',
  topicUnlockedCaption: 'НОВАЯ ТЕМА ОТКРЫТА',
  levelUpTitle: 'Новый уровень!',
  tapToContinue: 'Нажмите, чтобы продолжить',
  soundOnLabel: 'Выключить звук',
  soundOffLabel: 'Включить звук',
  allTopicsLink: 'Все темы',
  energyInfo: (n: number, max: number) => `Энергия: ${n}/${max}. Уменьшается на 1 за каждую ошибку, завтра восстановится.`,
  streakInfo: (n: number) => `Вы занимаетесь уже ${n} дней подряд. Сыграйте сегодня — и огонь не погаснет!`,
  streakToast: (n: number) => `Отлично! Уже ${n} дней подряд`,
  streakTitle: (n: number) => `${n} дней подряд!`,
  streakBody: 'Играйте хотя бы 1 раз в день',

  battleTitle: 'Математический батл',
  battleModeQuestion: 'Выберите режим',
  battleSameTitle: 'На своём уровне',
  battleSameBody: 'Соперники и вопросы подбираются под ваш уровень.',
  battleMixedTitle: 'Смешанный уровень',
  battleMixedBody: 'Играете с учениками любых уровней. Вопросы могут быть и лёгкими, и сложными.',
  battleFind: 'НАЙТИ СОПЕРНИКОВ',
  battleYourLevel: 'Ваш уровень',
  battleSearching: 'Поиск события…',
  battleFoundEvent: (n: number) => `Найдено открытое событие · №${n}`,
  battleCreatedEvent: (n: number) => `Создано новое событие · №${n} — вы первый`,
  battleFullSkip: 'Найденное событие заполнено — ищем другое…',
  battlePlayers: (a: number, b: number) => `${a}/${b}`,
  battleWaiting: 'Ожидание',
  battleAlmost: 'Почти заполнено',
  battleFullPill: 'Заполнено',
  battleLocked: 'Событие заполнено — новые игроки не принимаются',
  battleNeedMore: (n: number) => `Ждём ещё ${n} игроков…`,
  battleStartsSoon: 'Начало: скоро',
  battleStartsVerySoon: 'Начало: совсем скоро',
  battleLeft: (name: string) => `${name} вышел`,
  battleJoined: (name: string) => `${name} присоединился`,
  battleLeave: 'Выйти',
  battleGetReady: 'Приготовьтесь!',
  battleStart: 'СТАРТ',
  battleYou: 'Вы',
  battleRank: (n: number) => `${n}-е место`,
  battleLive: 'LIVE',
  battleResultsTitle: 'Батл завершён',
  battlePlayAgain: 'ЕЩЁ РАЗ',
  battleExit: 'ВЫЙТИ',
  battleScoreUnit: 'очков',
  levelShort: (n: number) => `L${n}`,

  missionHeader: 'Миссия недели',
  missionDaysLeft: (n: number) => `Осталось ${n} дн.`,
  missionProgress: (a: number, b: number) => `${a}/${b}`,
  unitsHeader: 'Разделы',
  unitLessonsOf: (a: number, b: number) => `${a}/${b} уроков`,

  shopFeatured: 'ТОВАР НЕДЕЛИ',
  shopCollection: 'Моя коллекция',
  shopGet: 'ПОЛУЧИТЬ',
  shopOwned: 'Ваше',
  shopProcessing: 'Оформляем…',
  shopSuccessTitle: 'Награда получена',
  shopSuccessBody: (name: string) => `${name} — добавлено в вашу коллекцию`,
  shopNeedMore: (n: string) => `Нужно ещё ${n} монет`,
  shopEarnHint: 'Монеты зарабатываются в играх и ежедневном челлендже',
  shopBalanceOf: (a: string, b: string) => `${a} / ${b}`,
  shopPriceCoins: (p: string) => `${p} монет`,

  notificationsTitle: 'Уведомления',
  markAllRead: 'Прочитать все',
  notifNewHeader: 'НОВЫЕ',
  notifOldHeader: 'РАНЕЕ',
  emptyNotifTitle: 'Уведомлений нет',
  emptyNotifBody: 'Новые сообщения появятся здесь.',

  langTitle: 'Язык',
  langUz: "O'zbekcha",
  langRu: 'Русский',
  langEn: 'English',

  errorTitle: 'Данные не загрузились',
  errorBody: 'Проверьте интернет и попробуйте снова.',
  errorRetry: 'ПОВТОРИТЬ',
  offline: (when: string) => `Нет интернета · Последние данные: ${when}`,
  offlineWhen: '12 августа, 14:30',
  back: 'Назад',

  avatarStudioTitle: 'Создайте аватар',
  avatarStudioSubtitle: 'Сделайте его своим',
  avatarSave: 'Сохранить',
  avatarSavedShort: 'Готово',
  avatarSaved: 'Аватар сохранён',
  avatarSaveError: 'Аватар не сохранился',
  avatarSaveErrorBody: 'Не удалось записать данные. Попробуйте ещё раз.',
  avatarRetry: 'Повторить',
  avatarKeepEditing: 'Продолжить',
  avatarDiscardTitle: 'Отменить изменения?',
  avatarDiscardBody: 'Несохранённые изменения будут потеряны.',
  avatarDiscard: 'Выйти без сохранения',
  avatarReset: 'Сначала',
  avatarResetTitle: 'Начать сначала?',
  avatarResetBody: 'Все настройки вернутся к аватару по умолчанию.',
  avatarResetConfirm: 'Сбросить',
  avatarClose: 'Закрыть',
  avatarEditLabel: 'Изменить аватар',
  avatarCatSkin: 'Кожа',
  avatarCatFace: 'Лицо',
  avatarCatEyes: 'Глаза',
  avatarCatBrows: 'Брови',
  avatarCatMouth: 'Рот',
  avatarCatHair: 'Волосы',
  avatarCatHeadwear: 'Шапки',
  avatarCatClothing: 'Одежда',
  avatarCatAccessories: 'Детали',
  avatarCatBackground: 'Фон',
  avatarCatHijab: 'Хиджаб',
  avatarTypeTitle: 'Для кого аватар?',
  avatarTypeSubtitle: 'Потом всё можно изменить',
  avatarBoy: 'Мальчик',
  avatarGirl: 'Девочка',
  avatarSwitchTitle: 'Сменить тип аватара?',
  avatarSwitchBody: 'Текущие настройки заменятся стандартным видом нового типа.',
  avatarSwitchConfirm: 'Сменить',
  avatarSwitchLabel: 'Сменить тип аватара',
  avatarNone: 'Нет',
  avatarColorHeader: 'Цвет',
  avatarStyleHeader: 'Стиль',
  avatarOptionLabel: (n: number) => `Вариант ${n}`,

  devTitle: 'PROTOTYPE CONTROLS',
  devTheme: 'Theme',
  devRole: 'Role',
  devLight: 'Light',
  devDark: 'Dark',
  devStudent: 'Student',
  devParent: 'Parent',
  devState: 'Data state',
  devGame: 'Game payment',
  devPaid: 'Paid',
  devUnpaid: 'Unpaid',
  devFull: 'Full',
  devLoading: 'Loading',
  devEmpty: 'Empty',
  devError: 'Error',
  devOffline: 'Offline',
  devRestart: 'Restart auth',

  profileOpenLabel: 'Открыть профиль',

  rankingTitle: 'Рейтинг',
  rankingSubtitle: 'По академическому показателю',
  rankScopeLevel: 'Мой уровень',
  rankScopeAll: 'Все уровни',
  rankModePerformance: 'Показатель',
  rankModeImprovement: 'Рост',
  rankTopStudents: 'Лучшие ученики',
  rankYourPosition: 'Ваше место',
  rankScore: 'Академический балл',
  rankMovementUp: (n: number) => `Поднялись на ${n} мест`,
  rankMovementDown: (n: number) => `Опустились на ${n} мест`,
  rankMovementNone: 'Место не изменилось',
  rankNoHistory: 'Нет данных для сравнения с прошлым месяцем',
  rankHowCalculated: 'Как считается балл?',
  rankFormulaIntro: 'Балл складывается из нескольких академических показателей:',
  rankComponentMastery: 'Освоение',
  rankComponentExams: 'Экзамены',
  rankComponentHomework: 'Домашние задания',
  rankComponentCurriculum: 'Программа',
  rankComponentConsistency: 'Регулярность',
  rankHowToMoveUp: 'Чтобы подняться выше',
  rankPointsBehind: (points: string, rank: number) => `До места #${rank} не хватает ${points} балла`,
  rankAdviceUnit: (unit: string) => `Повысьте освоение по теме «${unit}»`,
  rankAdviceHomework: 'Выполняйте домашние задания полностью',
  rankAdviceExam: 'Тщательно подготовьтесь к следующему экзамену',
  rankEmptyTitle: 'Рейтинг готовится',
  rankEmptyBody: 'Чтобы попасть в рейтинг, нужно ещё несколько оценок.',
  rankLevel: (level: string) => `Уровень ${level}`,

  pgSummary: (name: string, level: string) => `${name} сейчас на уровне ${level}`,
  pgGoalHeader: 'МОЯ ЦЕЛЬ',
  pgNow: 'Сейчас',
  pgTarget: 'Цель',
  pgTargetDate: (date: string) => `Срок: ${date}`,
  pgReadinessHeader: 'ГОТОВНОСТЬ',
  pgReadinessBasis: (done: number, total: number) =>
  `${done} из ${total} тем показаны на уровне цели`,
  pgReadinessUnknown: 'Для оценки готовности пока недостаточно данных',
  readinessStrong: 'Сильная готовность',
  readinessOnTrack: 'По плану',
  readinessNeedsWork: 'Нужно поработать',
  bandFoundation: 'Нужна база',
  bandDeveloping: 'Развивается',
  bandStrong: 'Сильно',
  bandMastered: 'Освоено',
  pgStrengths: 'СИЛЬНЫЕ СТОРОНЫ',
  pgWeak: 'ТРЕБУЕТ ВНИМАНИЯ',
  pgOverall: 'Общий прогресс',
  pgCompletedOf: (done: number, total: number) => `Пройдено ${done} из ${total} тем`,
  pgMetricTopics: 'Темы',
  pgMetricExams: 'Средний балл',
  pgExamLatest: 'Последний:',
  pgExamBest: 'лучший:',
  pgActivitySince: (date: string) => `с ${date}`,
  pgActivityAttended: (a: number, b: number) => `посетил ${a} из ${b} занятий`,
  pgRecentHeader: 'ПОСЛЕДНИЕ СОБЫТИЯ',
  pgActAttended: 'Посетил урок',
  pgActMissed: 'Пропустил урок',
  pgActHomework: 'Выполнил домашнюю работу',
  pgActExam: (score: string) => `Сдал экзамен — ${score} баллов`,
  pgMilestoneHeader: 'СЛЕДУЮЩИЙ ЭТАП',
  pgTopicsLeft: (n: number) => `Осталось ${n} тем`,
  pgContinue: 'Продолжить',
  pgLevelsHeader: 'УРОВНИ',

  chatTitle: 'Чаты',
  chatSearch: 'Поиск чата',
  chatSectionLearning: 'УЧЁБА',
  chatSectionSupport: 'ПОДДЕРЖКА',
  chatSectionAdmin: 'АДМИНИСТРАЦИЯ',
  chatOnline: 'В сети',
  chatYou: 'Вы',
  chatComposer: 'Напишите сообщение',
  chatSendLabel: 'Отправить',
  chatAttachLabel: 'Прикрепить файл',
  chatAttachSoon: 'Вложения появятся в следующей версии',
  chatDayToday: 'Сегодня',
  chatDayYesterday: 'Вчера',
  chatDayEarlier: 'Ранее',
  chatEmptyTitle: 'Чатов нет',
  chatEmptyBody: 'Здесь появятся ваша группа и поддержка.',
  chatThreadEmptyTitle: 'Начните разговор',
  chatThreadEmptyBody: 'Задайте вопрос по сегодняшнему уроку.',
  chatSupportQuick: 'С чем нужна помощь?',
  chatTopicPayment: 'Оплата',
  chatTopicTechnical: 'Техническая проблема',
  chatTopicAccount: 'Аккаунт',
  chatTopicCourse: 'Курс',
  chatSearchEmpty: 'Ничего не найдено',

  practiceHeader: 'ПЛАН ПРАКТИКИ',
  practiceIntro: 'План на неделю по слабым темам',
  practiceEmpty: 'Пока нет тем, требующих практики',

  lsSegCurriculum: 'Программа',
  lsSegAttendance: 'Посещаемость',
  lsCompletedOf: (done: number, total: number) => `Пройдено ${done} из ${total} тем`,
  lsStateCompleted: 'Пройдено',
  lsStateCurrent: 'Текущая',
  lsStateLocked: 'Закрыто',
  lsTopicsShort: (done: number, total: number) => `${done}/${total} тем`,
  lsLockedHint: (n: number) => `До открытия ещё ${n} тем`,
  lsLockedToast: 'Эта тема пока закрыта',
  lsContinueHere: 'Продолжайте отсюда',
  lsLesson: 'Текст урока',
  lsWatched: 'Просмотрено',
  lsNotWatched: 'Не просмотрено',
  lsExam: 'Экзамен',
  lsEmptyTitle: 'Программа не назначена',
  lsEmptyBody: 'Она появится здесь, как только группе назначат учебную программу.',
  lsExpandLevel: 'Раскрыть уровень',
  lsExpandModule: 'Раскрыть модуль',
  lsStepLearn: 'Изучение',
  lsStepPractice: 'Практика',
  lsPracticeHint: 'Практические задания',
  lsHomeworkNone: 'Не задано',
  lsAvailable: 'Доступно',
  lsWatchVideo: 'Смотреть видео',
  lsRewatch: 'Пересмотреть',
  lsVideoMissing: 'Видео ещё не загружено',
  lsVideoMissingBody: 'Оно откроется здесь после загрузки. Есть вопрос — напишите преподавателю.',
  lsAttClasses: 'Уроков',
  lsAttPresent: 'Посетил',
  lsAttRate: 'Посещаемость',
  lsAttEmpty: 'В этом месяце занятий не было',
  lsAttHint: 'Выберите день или листайте месяцы',
  lsDoneBadge: 'Завершено',
  lsExamResult: 'Результат экзамена',
  lsTopicsHeader: 'Темы',
  lsPracticeLocked: 'Откроется после просмотра видео',
  lsLevelLockedHint: 'Сначала завершите текущий уровень',
  pgActivityHeader: 'АКТИВНОСТЬ',
  pgLessonsTaken: 'Уроков пройдено',
  pgVideosWatched: 'Видео просмотрено',
  pgDuration: (h: number, m: number) => h > 0 ? `${h} ч ${m} мин` : `${m} мин`,
  soundRow: 'Звуковые эффекты'
};

const en: Strings = {
  monthsFull: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  monthsGen: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  weekdaysShort: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
  weekdaysLong: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],

  brand: 'Phoenix Math School',
  version: 'Phoenix Math School · v1.0',

  authWelcome: 'Welcome',
  authSubtitle: 'Sign in to your account',
  authIdLabel: 'ID number',
  authIdPlaceholder: '01234',
  authPasswordLabel: 'Password',
  authPasswordPlaceholder: '••••••••',
  authSignIn: 'SIGN IN',
  authForgot: 'Forgot your password? Contact the administrator.',
  authError: 'Wrong ID or password. Please try again.',
  authShowPassword: 'Show password',
  authHidePassword: 'Hide password',

  pwTitle: 'Set a new password',
  pwBody: 'Your first password was temporary. Choose one only you know.',
  pwNew: 'New password',
  pwRepeat: 'Repeat',
  pwRule8: 'At least 8 characters',
  pwRuleDigit: 'At least 1 digit',
  pwRuleMatch: 'Passwords match',
  pwSave: 'SAVE',

  bioTitle: 'Enable quick sign-in?',
  bioBody: 'So you never type your password again.',
  bioFace: 'ENABLE FACE ID',
  bioPin: 'Set a 4-digit PIN',
  bioSkip: 'Not now',

  pinTitle: 'Enter your PIN',
  pinWrong: 'Wrong PIN',
  pinDelete: 'Delete',
  pinFaceId: 'Face ID',

  tabToday: 'Today',
  tabLessons: 'Lessons',
  tabBookings: 'Booking',
  tabProgress: 'Progress',
  tabProfile: 'Profile',
  tabAttendance: 'Attendance',
  tabPayments: 'Payments',

  todayGreeting: (name: string) => `Hi, ${name}`,
  todayLessonCaption: "TODAY'S LESSON",
  todayNoLesson: 'No lesson today',
  todayNextLesson: 'Next lesson: tomorrow at 14:00',
  todayAllClear: 'All clear 👍',
  todayAllClearBody: 'Nothing left to do today.',
  nextBookingHeader: 'NEXT BOOKING',
  lastExamHeader: 'LAST EXAM',
  weakPointBody: 'Your teacher thinks this topic needs one more lesson.',
  weakPointCta: 'BOOK NOW',
  finishHeader: 'TO FINISH',

  statAttendance: 'Attendance',
  statHomework: 'Homework',
  statTopics: 'Topics',
  statLessons: 'Lessons',
  statPresent: 'Present',
  statPresentParent: 'Present',

  lessonsSubtitle: 'Every lesson and how it went',
  segAll: 'All',
  segAbsent: 'Missed',
  segHomework: 'Homework',
  lessonAttendance: 'Attendance',
  lessonHomework: 'Homework',
  lessonConspect: 'Notes',
  lessonEngagement: 'Engagement',
  emptyLessonsTitle: 'No lessons marked yet',
  emptyLessonsBody: 'They appear here once attendance is marked.',

  present: 'Present',
  late: 'Late',
  absent: 'Absent',
  unmarked: 'Unmarked',
  hwDone: 'Done',
  hwNot: 'Not done',
  hwPartial: 'Partial',
  conspectFull: 'Complete',
  conspectPartial: 'Partial',
  engHigh: 'High',
  engMedium: 'Medium',
  engLow: 'Low',

  bookingsSubtitle: 'Book a slot for an extra lesson',
  quotaLine: (left: number, limit: number) => `${left} of ${limit} left this week`,
  quotaSpent: 'Weekly limit reached. Booking reopens on Monday.',
  newBooking: 'NEW BOOKING',
  upcomingHeader: 'UPCOMING',
  pastHeader: 'PAST',
  bookingAttended: 'Attended',
  bookingMissed: 'Missed',
  bookingCancelled: 'Cancelled',
  bookingNeedsAnother: 'Needs another lesson',
  bookingLocked: 'Changes closed at 12:00.',
  swipeCancel: 'Cancel',
  emptyBookingsTitle: 'No bookings yet',
  emptyBookingsBody: 'Book a slot for an extra lesson.',

  sheetNewBooking: 'New booking',
  stepDate: 'DATE',
  stepTime: 'TIME',
  stepPurpose: 'PURPOSE',
  purposePlaceholder: 'e.g.: Fractions — common denominator',
  purposeHint: 'At least 3 characters.',
  confirm: 'CONFIRM',
  bookingConfirmed: 'Booking confirmed',
  cancelTitle: 'Cancel this booking?',
  cancelReasonLabel: 'Reason (at least 10 characters)',
  cancelReasonPlaceholder: 'Why are you cancelling? (min 10 chars)',
  cancelReasonHint: '10 to 300 characters.',
  cancelReasonMin: 'Reason must be at least 10 characters',
  cancelConfirm: 'CANCEL BOOKING',
  cancelBack: 'Back',
  cancelKeep: 'Keep booking',
  bookingCancelledToast: 'Booking cancelled',

  bookingTabBook: 'Book Session',
  bookingTabMine: 'My Bookings',
  weeklyUsageTitle: 'Weekly sessions',
  weeklyUsageRemaining: (rem: number) => `${rem} session${rem === 1 ? '' : 's'} remaining`,
  weeklyUsageLimitReached: 'Weekly limit reached',
  sessionsAvailable: 'Available sessions',
  noSlotsForDate: 'No sessions available for this date.',
  noUpcomingBookings: 'No upcoming sessions',
  noPastBookings: 'No past sessions',
  noCancelledBookings: 'No cancelled sessions',
  slotBookedCount: (count: number, cap: number) => `${count} / ${cap} booked`,
  slotStatusAvailable: 'Available',
  slotStatusAlmostFull: 'Almost full',
  slotStatusFull: 'Full',
  slotStatusClosed: 'Closed',
  slotStatusClash: 'Conflicts with class',
  confirmSession: 'Confirm session',
  confirmBookingButton: 'Confirm booking',
  rescheduleTitle: 'Reschedule session',
  rescheduleConfirm: 'RESCHEDULE',
  rescheduleSuccess: 'Booking rescheduled successfully',
  sameDayCutoffNotice: (time: string) => `Same-day cancellations close at ${time}`,
  todayDisabledNotice: 'Today is not bookable (must be booked 1 day ahead)',
  holidayNotice: 'School holiday',
  filterAll: 'All',
  filterUpcoming: 'Upcoming',
  filterPast: 'Past',
  filterCancelled: 'Cancelled',
  purposeLabel: 'Session purpose',

  progressSubtitle: 'Topics, exams and your work',
  curriculumHeader: 'CURRICULUM',
  examsHeader: 'EXAMS',
  supportHeader: 'EXTRA LESSONS',
  topicsProgress: (done: number, total: number) => `${done} / ${total} topics completed`,
  topicCompleted: 'Completed',
  topicInProgress: 'In progress',
  topicNotStarted: 'Not started',
  examPass: 'Passed',
  examConditional: 'Conditional',
  examFail: 'Failed',
  examViewScan: 'View work',
  examNoScan: 'No scan',
  examScoreUnit: 'pts',
  emptyTopicsTitle: 'Curriculum not set yet',
  emptyExamsTitle: 'No exams taken yet',

  contactHeader: 'CONTACT',
  phoneLabel: 'Phone',
  phoneSheetTitle: 'Phone number',
  phoneNote: 'The school calls this number. Changes are logged.',
  save: 'SAVE',
  saved: 'Changes saved',
  settingsHeader: 'SETTINGS',
  notificationsRow: 'Notifications',
  languageRow: 'Language',
  darkModeRow: 'Dark mode',
  pinRow: 'PIN code',
  schoolHeader: 'SCHOOL INFO',
  schoolNote: 'Only the administrator can change this information.',
  levelLabel: 'Level',
  groupLabel: 'Group',
  statusLabel: 'Status',
  teacherLabel: 'Teacher',
  loginLabel: 'Login',
  logout: 'SIGN OUT',
  photoUpload: 'Upload photo',
  photoCamera: 'Take photo',
  photoDelete: 'Delete photo',
  cancel: 'Cancel',
  close: 'Close',
  childrenHeader: 'MY CHILDREN',
  notifPrefsHeader: 'NOTIFICATIONS',
  notifPrefAbsent: 'Missed a lesson',
  notifPrefHw: 'Homework not done',
  notifPrefDue: 'Payment reminder',
  notifPrefPaid: 'Payment received',
  notifPrefExam: 'Exam result',
  notifPrefNote: 'No more than 3 messages a day.',

  parentPresent: (name: string) => `${name} attended the lesson`,
  parentLate: (name: string) => `${name} was late`,
  parentAbsent: (name: string) => `${name} missed the lesson`,
  parentUnmarked: (name: string) => `Attendance not marked for ${name}`,
  debtTitle: (sum: string) => `${sum} UZS due`,
  debtCta: 'VIEW PAYMENTS',
  debtAllChildren: (sum: string) => `Across all children: ${sum} UZS`,
  allPaid: 'All paid',

  balanceCaption: 'DUE',
  monthsHeader: 'MONTHS',
  paid: 'Paid',
  writtenOff: 'Written off',
  debtPill: (sum: string) => `${sum} due`,
  charged: 'Charged',
  paidRow: 'Paid',
  remainder: 'Balance',
  receiptsHeader: 'RECEIPTS',
  receiptVoided: 'Voided',
  chequeGiven: 'Paper receipt issued',
  paymentsFooter: 'If something looks wrong, contact the administrator — they keep the paper receipts.',
  emptyChargesTitle: 'No charges yet',
  currency: 'UZS',
  receiptTo: 'To',
  receiptId: 'ID',
  receiptMonth: 'Month',
  receiptMethod: 'Method',
  receiptTakenBy: 'Received by',
  receiptNo: 'Receipt no.',
  receiptShare: 'SHARE',
  receiptPdf: 'PDF',
  receiptVoidedBanner: 'This receipt has been voided',
  shared: 'Receipt shared',

  legendPresent: 'Present',
  legendLate: 'Late',
  legendAbsent: 'Absent',

  tabGame: 'Play',
  arenaSubtitle: '5 minutes a day — big results',
  arenaLevel: (n: number) => `Level ${n}`,
  arenaXp: (has: number, need: number) => `${has} / ${need} XP`,
  questsHeader: 'DAILY QUESTS',
  unitHeader: (n: number) => `UNIT ${n}`,
  unitProgress: (done: number, total: number) => `${done}/${total}`,
  startLesson: 'START',
  levelLocked: 'Finish the previous level first',
  leagueHeader: 'LEAGUE',
  leagueName: 'Silver League',
  leagueSub: 'Weekly XP ranking',
  leagueYou: 'You',
  leaguePromoZone: 'PROMOTION ZONE — Gold League',
  leagueDemoteZone: 'DEMOTION ZONE — Bronze',
  leagueEnds: 'Ends Sunday at midnight',
  leaguePlace: (n: number) => `#${n}`,
  tierBronze: 'Bronze',
  tierSilver: 'Silver',
  tierGold: 'Gold',
  tierDiamond: 'Diamond',
  shopTitle: 'Shop',
  shopRowTitle: 'Shop',
  shopRowSub: 'Trade coins for rewards',
  shopVouchers: 'VOUCHERS',
  shopMerch: 'PHOENIX MERCH',
  shopBoosts: 'BOOSTS',
  shopBalance: 'YOUR COINS',
  buy: 'BUY',
  bought: (name: string) => `${name} — purchased ✓`,
  notEnoughCoins: 'Not enough coins',
  energyIsFull: 'Energy is already full',
  popularPill: 'TOP',
  coinsUnit: 'coins',
  gameLockPill: 'Payment pending',
  gameLockTitle: 'Play is temporarily locked',
  gameLockBody: 'The monthly payment has not been received yet. Play, shop and arena reopen after payment.',
  gameLockFoot: 'Payments are made in the Payments section of the parent app.',
  playCheck: 'CHECK',
  playContinue: 'CONTINUE',
  playCorrect: 'Correct!',
  playWrong: 'Incorrect',
  playAnswerWas: (a: string) => `Correct answer: ${a}`,
  playCombo: (n: number) => `${n} in a row`,
  playQuestionOf: (i: number, n: number) => `Question ${i} / ${n}`,
  playResultsGreat: 'Excellent work!',
  playResultsOk: 'Good try!',
  playXp: 'XP',
  playCoins: 'Coins',
  playAccuracy: 'Accuracy',
  playNoEnergyTitle: 'Out of energy',
  playNoEnergyBody: 'Refills tomorrow — or refill instantly in the shop.',
  playFinish: 'FINISH',
  playPlusXp: (n: number) => `+${n} XP`,

  catAll: 'All',
  catPath: 'Home',
  catBattle: 'Arena',
  catSpeed: 'Sprint',
  catDaily: 'Daily',
  catPractice: 'Practice',
  catLife: 'Real life',
  battleHeroCaption: 'LIVE COMPETITION',
  battleHeroTitle: 'Math Battle',
  battleHeroBody: '10 players · 5 questions · fastest wins',
  battleHeroCta: 'ENTER ARENA',
  battleStats: (w: number, p: number) => `${w} wins · ${p} games`,
  dailyTitle: 'Daily challenge',
  dailyBody: '5 questions · matched to your level · streak bonus',
  dailyBonus: (n: number) => `Streak bonus: +${n}`,
  dailyDone: "Today's challenge completed",
  doneLabel: 'Done',
  sprintTitle: 'Mental sprint',
  sprintBody: 'Max problems in 60 seconds',
  sprintBest: (n: number) => `Best: ${n}`,
  sprintGo: 'START',
  sprintScore: 'Score',
  sprintNewRecord: 'New record!',
  sprintTimeUp: "Time's up",
  reviewTitle: 'Smart review',
  reviewBody: 'Built from weak topics and exam mistakes',
  reviewSource: 'Fractions · Decimals',
  lifeTitle: 'Real-life math',
  lifeBody: 'Percentages, discounts, loans — practical numbers',
  lifeMeta: (n: number) => `${n} problems`,
  tournamentCta: 'Register',
  tournamentJoined: 'Registered for the tournament ✓',
  tournamentSoon: (d: string) => `${d} · live final at the center`,
  allUnitsRow: 'All units',
  unitsScreenTitle: 'Curriculum',

  topicCaption: (n: number) => `MATHEMATICS · TOPIC ${n}`,
  topicGamesOf: (a: number, b: number) => `${a}/${b} games`,
  topicMastery: (p: number) => `${p}% mastered`,
  nextTopicCaption: 'NEXT TOPIC',
  nextTopicLock: 'Unlocks after beating the boss',
  nextTopicReward: (n: number) => `On unlock: +${n} coins`,
  pathBattleTitle: 'Battle',
  pathBattleSub: 'Live 10-player match',
  pathBattleLocked: 'Unlocks after the boss',
  topicDoneTitle: 'Topic complete!',
  topicUnlockedCaption: 'NEW TOPIC UNLOCKED',
  levelUpTitle: 'Level up!',
  tapToContinue: 'Tap to continue',
  soundOnLabel: 'Mute sound',
  soundOffLabel: 'Unmute sound',
  allTopicsLink: 'All topics',
  energyInfo: (n: number, max: number) => `Energy: ${n}/${max}. Drops by 1 for each wrong answer, refills tomorrow.`,
  streakInfo: (n: number) => `You've practiced ${n} days in a row. Play today to keep the flame alive!`,
  streakToast: (n: number) => `Great! ${n} days in a row`,
  streakTitle: (n: number) => `${n} days in a row!`,
  streakBody: 'Play at least one game every day',

  battleTitle: 'Math Battle',
  battleModeQuestion: 'Choose a mode',
  battleSameTitle: 'Your level',
  battleSameBody: 'Opponents and questions are matched to your level.',
  battleMixedTitle: 'Mixed levels',
  battleMixedBody: 'Play against students of any level. Questions may be easy or hard.',
  battleFind: 'FIND MATCH',
  battleYourLevel: 'Your level',
  battleSearching: 'Searching for an event…',
  battleFoundEvent: (n: number) => `Open event found · #${n}`,
  battleCreatedEvent: (n: number) => `New event created · #${n} — you are first`,
  battleFullSkip: 'That event is full — searching for another…',
  battlePlayers: (a: number, b: number) => `${a}/${b}`,
  battleWaiting: 'Waiting',
  battleAlmost: 'Almost full',
  battleFullPill: 'Full',
  battleLocked: 'Event full — no new players accepted',
  battleNeedMore: (n: number) => `Waiting for ${n} more players…`,
  battleStartsSoon: 'Starting: soon',
  battleStartsVerySoon: 'Starting: very soon',
  battleLeft: (name: string) => `${name} left`,
  battleJoined: (name: string) => `${name} joined`,
  battleLeave: 'Leave',
  battleGetReady: 'Get ready!',
  battleStart: 'START',
  battleYou: 'You',
  battleRank: (n: number) => `#${n}`,
  battleLive: 'LIVE',
  battleResultsTitle: 'Battle finished',
  battlePlayAgain: 'PLAY AGAIN',
  battleExit: 'EXIT',
  battleScoreUnit: 'pts',
  levelShort: (n: number) => `L${n}`,

  missionHeader: 'Weekly mission',
  missionDaysLeft: (n: number) => `${n} days left`,
  missionProgress: (a: number, b: number) => `${a}/${b}`,
  unitsHeader: 'Units',
  unitLessonsOf: (a: number, b: number) => `${a}/${b} lessons`,

  shopFeatured: 'FEATURED',
  shopCollection: 'My collection',
  shopGet: 'GET',
  shopOwned: 'Owned',
  shopProcessing: 'Processing…',
  shopSuccessTitle: 'Reward unlocked',
  shopSuccessBody: (name: string) => `${name} added to your collection`,
  shopNeedMore: (n: string) => `You need ${n} more coins`,
  shopEarnHint: 'Earn coins in games and the daily challenge',
  shopBalanceOf: (a: string, b: string) => `${a} / ${b}`,
  shopPriceCoins: (p: string) => `${p} coins`,

  notificationsTitle: 'Notifications',
  markAllRead: 'Mark all read',
  notifNewHeader: 'NEW',
  notifOldHeader: 'EARLIER',
  emptyNotifTitle: 'No notifications',
  emptyNotifBody: 'New messages appear here.',

  langTitle: 'Language',
  langUz: "O'zbekcha",
  langRu: 'Русский',
  langEn: 'English',

  errorTitle: "Couldn't load data",
  errorBody: 'Check your connection and try again.',
  errorRetry: 'RETRY',
  offline: (when: string) => `No internet · Last data: ${when}`,
  offlineWhen: 'Aug 12, 14:30',
  back: 'Back',

  avatarStudioTitle: 'Create your avatar',
  avatarStudioSubtitle: 'Make it yours',
  avatarSave: 'Save',
  avatarSavedShort: 'Saved',
  avatarSaved: 'Avatar saved',
  avatarSaveError: "Couldn't save your avatar",
  avatarSaveErrorBody: "Couldn't write to device storage. Please try again.",
  avatarRetry: 'Retry',
  avatarKeepEditing: 'Keep editing',
  avatarDiscardTitle: 'Discard changes?',
  avatarDiscardBody: 'Your unsaved changes will be lost.',
  avatarDiscard: 'Discard',
  avatarReset: 'Start over',
  avatarResetTitle: 'Start over?',
  avatarResetBody: 'Everything goes back to the default avatar.',
  avatarResetConfirm: 'Reset',
  avatarClose: 'Close',
  avatarEditLabel: 'Edit avatar',
  avatarCatSkin: 'Skin',
  avatarCatFace: 'Face',
  avatarCatEyes: 'Eyes',
  avatarCatBrows: 'Brows',
  avatarCatMouth: 'Mouth',
  avatarCatHair: 'Hair',
  avatarCatHeadwear: 'Headwear',
  avatarCatClothing: 'Clothes',
  avatarCatAccessories: 'Extras',
  avatarCatBackground: 'Backdrop',
  avatarCatHijab: 'Hijab',
  avatarTypeTitle: 'Who is this avatar for?',
  avatarTypeSubtitle: 'You can change everything later',
  avatarBoy: 'Boy',
  avatarGirl: 'Girl',
  avatarSwitchTitle: 'Switch avatar type?',
  avatarSwitchBody: 'Your customization will be replaced with the default style for the new type.',
  avatarSwitchConfirm: 'Switch',
  avatarSwitchLabel: 'Switch avatar type',
  avatarNone: 'None',
  avatarColorHeader: 'Color',
  avatarStyleHeader: 'Style',
  avatarOptionLabel: (n: number) => `Style ${n}`,

  devTitle: 'PROTOTYPE CONTROLS',
  devTheme: 'Theme',
  devRole: 'Role',
  devLight: 'Light',
  devDark: 'Dark',
  devStudent: 'Student',
  devParent: 'Parent',
  devState: 'Data state',
  devGame: 'Game payment',
  devPaid: 'Paid',
  devUnpaid: 'Unpaid',
  devFull: 'Full',
  devLoading: 'Loading',
  devEmpty: 'Empty',
  devError: 'Error',
  devOffline: 'Offline',
  devRestart: 'Restart auth',

  profileOpenLabel: 'Open profile',

  rankingTitle: 'Ranking',
  rankingSubtitle: 'By academic performance',
  rankScopeLevel: 'My level',
  rankScopeAll: 'All levels',
  rankModePerformance: 'Performance',
  rankModeImprovement: 'Improvement',
  rankTopStudents: 'Top students',
  rankYourPosition: 'Your position',
  rankScore: 'Academic score',
  rankMovementUp: (n: number) => `Up ${n} places this month`,
  rankMovementDown: (n: number) => `Down ${n} places this month`,
  rankMovementNone: 'No change',
  rankNoHistory: 'No comparison data for last month',
  rankHowCalculated: 'How is the score calculated?',
  rankFormulaIntro: 'The score combines several academic signals:',
  rankComponentMastery: 'Mastery',
  rankComponentExams: 'Exams',
  rankComponentHomework: 'Homework',
  rankComponentCurriculum: 'Curriculum',
  rankComponentConsistency: 'Consistency',
  rankHowToMoveUp: 'To move up',
  rankPointsBehind: (points: string, rank: number) => `You are ${points} points behind #${rank}`,
  rankAdviceUnit: (unit: string) => `Raise your mastery in ${unit}`,
  rankAdviceHomework: 'Complete every homework assignment',
  rankAdviceExam: 'Prepare thoroughly for the next exam',
  rankEmptyTitle: 'Ranking is being prepared',
  rankEmptyBody: 'Complete a few more assessments to appear in the ranking.',
  rankLevel: (level: string) => `Level ${level}`,

  pgSummary: (name: string, level: string) => `${name} is at level ${level}`,
  pgGoalHeader: 'MY GOAL',
  pgNow: 'Now',
  pgTarget: 'Target',
  pgTargetDate: (date: string) => `Target date: ${date}`,
  pgReadinessHeader: 'READINESS',
  pgReadinessBasis: (done: number, total: number) =>
  `${done} of ${total} topics demonstrated at the target level`,
  pgReadinessUnknown: 'We need more assessment data to estimate your readiness',
  readinessStrong: 'Strong readiness',
  readinessOnTrack: 'On track',
  readinessNeedsWork: 'Needs work',
  bandFoundation: 'Needs foundation',
  bandDeveloping: 'Developing',
  bandStrong: 'Strong',
  bandMastered: 'Mastered',
  pgStrengths: 'STRONGEST AREAS',
  pgWeak: 'NEEDS ATTENTION',
  pgOverall: 'Overall progress',
  pgCompletedOf: (done: number, total: number) => `${done} of ${total} topics completed`,
  pgMetricTopics: 'Topics',
  pgMetricExams: 'Exam average',
  pgExamLatest: 'Latest:',
  pgExamBest: 'best:',
  pgActivitySince: (date: string) => `since ${date}`,
  pgActivityAttended: (a: number, b: number) => `attended ${a} of ${b} classes`,
  pgRecentHeader: 'RECENT ACTIVITY',
  pgActAttended: 'Attended a class',
  pgActMissed: 'Missed a class',
  pgActHomework: 'Completed homework',
  pgActExam: (score: string) => `Took an exam — ${score}`,
  pgMilestoneHeader: 'NEXT MILESTONE',
  pgTopicsLeft: (n: number) => `${n} topics remaining`,
  pgContinue: 'Continue',
  pgLevelsHeader: 'LEVELS',

  chatTitle: 'Chat',
  chatSearch: 'Search conversations',
  chatSectionLearning: 'MY LEARNING',
  chatSectionSupport: 'SUPPORT',
  chatSectionAdmin: 'ADMINISTRATION',
  chatOnline: 'Online',
  chatYou: 'You',
  chatComposer: 'Type your message',
  chatSendLabel: 'Send',
  chatAttachLabel: 'Attach a file',
  chatAttachSoon: 'Attachments arrive in a later version',
  chatDayToday: 'Today',
  chatDayYesterday: 'Yesterday',
  chatDayEarlier: 'Earlier',
  chatEmptyTitle: 'No conversations',
  chatEmptyBody: 'Your group and support will appear here.',
  chatThreadEmptyTitle: 'Start the conversation',
  chatThreadEmptyBody: 'Ask a question about today’s lesson.',
  chatSupportQuick: 'What do you need help with?',
  chatTopicPayment: 'Payment',
  chatTopicTechnical: 'Technical issue',
  chatTopicAccount: 'Account',
  chatTopicCourse: 'Course',
  chatSearchEmpty: 'Nothing found',

  practiceHeader: 'PRACTICE PLAN',
  practiceIntro: 'This week’s plan for your weak topics',
  practiceEmpty: 'Nothing needs practice right now',

  lsSegCurriculum: 'Curriculum',
  lsSegAttendance: 'Attendance',
  lsCompletedOf: (done: number, total: number) => `${done} of ${total} topics completed`,
  lsStateCompleted: 'Completed',
  lsStateCurrent: 'Current',
  lsStateLocked: 'Locked',
  lsTopicsShort: (done: number, total: number) => `${done}/${total} topics`,
  lsLockedHint: (n: number) => `${n} more topics to unlock`,
  lsLockedToast: 'This topic is not open yet',
  lsContinueHere: 'Continue from here',
  lsLesson: 'Lesson',
  lsWatched: 'Watched',
  lsNotWatched: 'Not watched',
  lsExam: 'Exam',
  lsEmptyTitle: 'No curriculum assigned',
  lsEmptyBody: 'It will appear here once your group is assigned a curriculum.',
  lsExpandLevel: 'Expand level',
  lsExpandModule: 'Expand module',
  lsStepLearn: 'Learn',
  lsStepPractice: 'Practice',
  lsPracticeHint: 'Practice exercises',
  lsHomeworkNone: 'Not assigned',
  lsAvailable: 'Available',
  lsWatchVideo: 'Watch video',
  lsRewatch: 'Watch again',
  lsVideoMissing: 'Video is not uploaded yet',
  lsVideoMissingBody: 'It will open here once uploaded. Message your teacher if you have a question.',
  lsAttClasses: 'Classes',
  lsAttPresent: 'Attended',
  lsAttRate: 'Attendance',
  lsAttEmpty: 'No classes this month',
  lsAttHint: 'Pick a day or swipe between months',
  lsDoneBadge: 'Completed',
  lsExamResult: 'Exam result',
  lsTopicsHeader: 'Topics',
  lsPracticeLocked: 'Unlocks after the video',
  lsLevelLockedHint: 'Finish your current level first',
  pgActivityHeader: 'ACTIVITY',
  pgLessonsTaken: 'Lessons taken',
  pgVideosWatched: 'Videos watched',
  pgDuration: (h: number, m: number) => h > 0 ? `${h}h ${m}m` : `${m}m`,
  soundRow: 'Sound effects'
};

const DICTS: Record<Locale, Strings> = { uz, ru, en };

export const LOCALES: {code: Locale;label: string;}[] = [
{ code: 'uz', label: "O'zbekcha" },
{ code: 'ru', label: 'Русский' },
{ code: 'en', label: 'English' }];


const STORAGE_KEY = 'phoenix.locale';

let currentLocale: Locale = 'uz';

/** Live binding — importers always see the active dictionary. */
export let t: Strings = uz;

export function setLocale(locale: Locale): void {
  currentLocale = locale;
  t = DICTS[locale];
  try {
    window.localStorage.setItem(STORAGE_KEY, locale);
  } catch {
    /* storage unavailable */
  }
}

export function getLocale(): Locale {
  return currentLocale;
}

export function localeLabel(locale: Locale): string {
  return LOCALES.find((l) => l.code === locale)?.label ?? locale;
}

export function loadStoredLocale(): Locale {
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === 'uz' || saved === 'ru' || saved === 'en') return saved;
  } catch {
    /* storage unavailable */
  }
  return 'uz';
}
